# Generated by Django 5.2 on 2025-05-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
